### ISSUE TITLE
Network Analysis Made Simple SetUp: Facing issue with ""Rebuild and Reopen in Container"

### ISSUE THREAD

**Issue by VineetKhatwal** [ericmjl/Network-Analysis-Made-Simple#287]
Following the steps mentioned in -
https://ericmjl.github.io/Network-Analysis-Made-Simple/00-preface/01-setup/

Facing the following issue with "Rebuild and Reopen in Container" -

<img width="1114" alt="Screen Shot 2022-04-24 at 3 44 21 PM" src="https://user-images.githubusercontent.com/48118060/164999992-ca4ba0f8-7e02-43eb-b57e-9a6f3ea3dd0b.png">

NOTE: Docker is already installed on my machine.

**Comment by MridulS** [comment]
Thanks for the report! Are you behind a proxy or a corporate firewall?

**Comment by elkninja** [comment]
i appear to be having the same issue.  no proxy or firewall.

**Comment by MridulS** [comment]
Anaconda.org was having some issues in the last couple of days so it's possible the packages weren't downloaded (and getting 404). Could you try again, hopefully this fixes it.

**Comment by ericmjl** [comment]
My analysis of the issue matches that of Mridul's intuition. Leaving the following notes primarily for myself and for future reference.

Two packages could not be found: 

<img width="450" alt="image" src="https://user-images.githubusercontent.com/2631566/165837281-21677802-5c65-4e73-88df-884cdc21bca0.png">

The `environment.yml` file pulls packages from `conda-forge`. If something is blocking downloads from `conda-forge`, which is hosted by `anaconda.org`, then those problems might show up. Being an interconnected system, package distribution is kind of difficult to debug. Others were able to set up the container during the tutorial. That makes debugging what went wrong in these two specific instances a bit difficult.

On account of successful container builds, I am going to close the issue. That doesn't mean I we won't address it, just that we need to see it happen live in order to really debug what's going on. 

As for M1 vs. Intel, nxviz is a pure Python package, and is reflected as such on the [conda-forge recipe](https://github.com/conda-forge/nxviz-feedstock/blob/main/recipe/meta.yaml) and the [conda-forge package page](https://anaconda.org/conda-forge/nxviz). My prior is that architecture is probably not the source of issues, but of course, we can't rule it out immediately.
